version: "3.9"
services:
  app:
    environment:
      - TZ=Europe/Moscow
    build: .
    env_file:
      - .env
    expose:
      - "8080"
    networks:
      - web
      - vnutri_net
  caddy:
    image: caddy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./.env:/app/.env:ro   # путь в контейнере
    depends_on:
      - app
    networks:
      - web
networks:
  web:
  vnutri_net:
    external: true
    name: vnutri-telegram-bot_default
volumes:
  caddy_data:
  caddy_config:
